include(
    ":buildSrc",
    ":app",
    ":core:uiGears",
    ":core:test:unitTest",
    ":core:test:integrationTest",
    ":core:extensions",
    ":core:injections",
    ":data:remote",
    ":data:local",
    ":features:login",
    ":features:home:homeContainer",
    ":features:home:newsList",
    ":features:home:newsFavorites"
)
